"""Render the maintained Q&A Markdown into the static newbie guide.

python -m pip install -r requirements-dev.txt
python scripts/build-guide-qa.py [--check]
"""

import argparse
import posixpath
import re
from pathlib import Path
from urllib.parse import quote, urlsplit
import xml.etree.ElementTree as ET

import markdown


ROOT = Path(__file__).resolve().parents[1]
GUIDE = ROOT / "docs/newbie-guide"
DOCUMENTS = [
    ("community-qa.md", "qa-tw", "TW 社区问答 · 44 问", 44),
    ("tavern-cards-community-qa.md", "qa-cards", "Tavern Cards 社区问答 · 51 问", 51),
]


def serialize(element):
    return ET.tostring(element, encoding="unicode", method="html")


def public_href(href, in_page=False):
    if href.startswith("#") or urlsplit(href).scheme:
        return href
    if href == "newbie-guide/index.html":
        return "#top" if in_page else "https://liarmttt.github.io/TavernWeave/"
    target = posixpath.normpath("docs/" + href)
    return "https://github.com/LiarMTTT/TavernWeave/blob/main/" + quote(target, safe="/#")


def adapt_elements(tree):
    # These pages are deployed on their own: repository-relative links must
    # resolve to GitHub, while the tutorial itself stays on this site.
    for link in tree.iter("a"):
        href = link.get("href", "")
        link.set("href", public_href(href, in_page=True))
    for parent in list(tree.iter()):
        for child in list(parent):
            if child.tag not in ("table", "pre"):
                continue
            index = list(parent).index(child)
            parent.remove(child)
            wrapper = ET.Element("div", {"class": "table-wrap" if child.tag == "table" else "code-block"})
            if child.tag == "pre":
                label = ET.SubElement(wrapper, "div", {"class": "code-label"})
                ET.SubElement(label, "span").text = "示例 / 命令"
                ET.SubElement(label, "button", {"class": "copy-btn", "type": "button"}).text = "复制"
            wrapper.append(child)
            parent.insert(index, wrapper)


def render_document(filename, prefix, title, expected):
    source = (ROOT / "docs" / filename).read_text(encoding="utf-8-sig")
    rendered = markdown.markdown(source, extensions=["tables", "fenced_code", "sane_lists"], output_format="xhtml")
    tree = ET.fromstring("<div>" + rendered + "</div>")
    adapt_elements(tree)
    section = ET.Element("section", {"class": "section qa-section", "id": prefix})
    head = ET.SubElement(section, "div", {"class": "section-head"})
    ET.SubElement(head, "div", {"class": "section-no"}).text = "QA"
    ET.SubElement(ET.SubElement(head, "div"), "h2").text = title
    actions = ET.SubElement(section, "div", {"class": "qa-actions"})
    ET.SubElement(actions, "a", {"class": "ghost-btn", "href": f"./resources/{filename}", "download": filename}).text = "下载完整 MD"
    ET.SubElement(actions, "button", {"class": "ghost-btn", "type": "button", "data-qa-expand": ""}).text = "展开全部答案"
    ET.SubElement(actions, "button", {"class": "ghost-btn", "type": "button", "data-qa-collapse": ""}).text = "收起全部答案"
    question = None
    count = 0
    group = 0
    for element in tree:
        text = "".join(element.itertext())
        if element.tag == "h1":
            # Keep the supplied title, including its author-review status.
            element.tag = "p"
            element.set("class", "qa-original-title muted")
        if element.tag == "h2":
            question = None
            element.tag = "h3"
            if re.match(r"[一二三四五六七]、", text):
                group += 1
                element.set("id", f"{prefix}-group-{group}")
            section.append(element)
        elif element.tag == "h3" and re.match(r"Q\d+\.", text):
            count += 1
            number = int(re.match(r"Q(\d+)\.", text).group(1))
            if number != count:
                raise ValueError(f"{filename}: question numbering is not sequential")
            question = ET.SubElement(section, "details", {"class": "qa-item", "id": f"{prefix}-q{number:02}"})
            element.tag = "summary"
            question.append(element)
            question = ET.SubElement(question, "div", {"class": "qa-answer"})
        elif question is not None:
            question.append(element)
        else:
            section.append(element)
    if count != expected:
        raise ValueError(f"{filename}: expected {expected} questions, got {count}; update the guide labels too")
    return serialize(section) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed HTML/downloads differ from the Markdown")
    args = parser.parse_args()
    output = "<!-- Generated by scripts/build-guide-qa.py. Edit docs/*community-qa.md. -->\n"
    output += "\n".join(render_document(*document) for document in DOCUMENTS)
    files = {GUIDE / "community-qa-content.html": output.encode("utf-8")}
    for filename, *_ in DOCUMENTS:
        source = (ROOT / "docs" / filename).read_text(encoding="utf-8-sig")
        # Exported files must remain useful outside the repository too.
        exported = re.sub(r"(\[[^\]\n]+\]\()([^\n)]+)(\))", lambda m: m[1] + public_href(m[2]) + m[3], source)
        files[GUIDE / "resources" / filename] = exported.encode("utf-8")
    stale = []
    for path, content in files.items():
        if path.exists() and path.read_bytes() == content:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    if stale:
        raise SystemExit("Q&A pages need rebuilding:\n" + "\n".join(stale))
    print("Q&A verified: 44 + 51 questions; 2 complete Markdown downloads" if args.check else "Q&A pages built: 44 + 51 questions")


if __name__ == "__main__":
    main()
